---

- name: Get AWS Cluster Config
  shell:
    cmd: |
      aws eks --profile {{ aws_profile }} --region {{ aws_region }} update-kubeconfig --name {{ aws_cluster_name }} --alias aws-csye7220-cluster

- name: Get GCP Cluster Config
  shell:
    cmd: |
      GET_CMD="gcloud container clusters describe {{ gke_cluster_name }} --region={{ gke_region }}"
      cat > {{ playbook_dir }}/gcp-kube-config.yaml<<EOF
      apiVersion: v1
      kind: Config
      current-context: csye7220-gcp-gke-cluster
      contexts: [{name: csye7220-gcp-gke-cluster, context: {cluster: gcp-csye7220-cluster, user: user-gcp}}]
      users: [{name: user-gcp, user: {auth-provider: {name: gcp}}}]
      clusters:
      - name: gcp-csye7220-cluster
        cluster:
          server: "https://$(eval "$GET_CMD --format='value(endpoint)'")"
          certificate-authority-data: "$(eval "$GET_CMD --format='value(masterAuth.clusterCaCertificate)'")"
      EOF

