---
- name: "Setup the AWS and GCP Config"
  hosts: localhost
  gather_facts: no
  roles:
    - kube-cluster

- name: "Copy Kube Context"
  hosts: jenkins
  become: yes
  gather_facts: no
  roles:
    - copy-kube-config