---
- name: Add NGINX repo
  community.kubernetes.helm_repository:
    name: nginx-edge
    repo_url: "https://helm.nginx.com/edge"

- name: Add K8s jetstack repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Helm repo update
  shell: "helm repo update"

- name: Install NGINX Ingress Helm Chart
  shell: "helm install --create-namespace --namespace ingress nginx-ingress nginx-edge/nginx-ingress --devel"

- name: Wait till the Pod is Ready
  community.kubernetes.k8s_info:
    kind: Pod
    wait: yes
    label_selectors:
      - app = nginx-ingress-nginx-ingress
    namespace: ingress
    wait_sleep: 10
    wait_timeout: 360
    wait_condition:
      type: Ready
      status: True
