---
- name: Transfer GCP config
  copy:
    src: "{{ playbook_dir }}/service-account-credentials.json"
    dest: /var/lib/jenkins/.kube/
    mode: 0600
    owner: jenkins
    group: jenkins

- name: Transfer AWS config
  copy:
    src: "{{ local_aws_dir }}"
    dest: /var/lib/jenkins/
    mode: 0600
    owner: jenkins
    group: jenkins

- name: Transfer kube context
  copy:
    src: "{{ local_kube_dir }}/config"
    dest: /var/lib/jenkins/.kube/
    mode: 0600
    owner: jenkins
    group: jenkins

- name: Copy the kubeconfig to jenkin
  copy:
    src: "{{ playbook_dir }}/gcp-kube-config.yaml"
    dest: /var/lib/jenkins/.kube/
    mode: 0600
    owner: jenkins
    group: jenkins

